from pydantic import BaseModel, Field, ValidationError
from typing import Dict, Type, Any, Optional, Literal, List
import inspect

from src.agent.tool import base_tool
from src.runtime import python_executor
from src.runtime import workspace
class ExecutePythonCodeTool(base_tool.BaseTool):
    """
    description:
        Executes valid Python code snippets, returns the console output generated by the code (e.g., printed results, return values) or detailed error messages (e.g., syntax errors, runtime errors) if execution fails.
    note:
        1. Compatible with Python versions 3.12
        2. The code environment that was executed last time still exists and can be used directly. 
        3. Be careful not to conflict with the naming.
    """
    python_code_snippet: str = Field(
        ..., 
        description=(
            "The valid Python code snippet to be executed. Must not contain malicious code (e.g., code that modifies system files, accesses sensitive data, or executes infinite loops). Code should be self-contained unless dependencies are specified in 'execution_context'"
        ),
        examples=["print('Hello, World!')"]
    )

    def run(self) -> str:
        execution_context: Optional[Dict[str, Any]] = workspace.initialize_workspace()
        return python_executor.run(self.python_code_snippet, execution_context)
