CallToolResult(
    content=[
        TextContent(
            type="text",
            text='{"total_count":977,"incomplete_results":false,"items":[{"id":10270250,"name":"react","full_name":"facebook/react","description":"The library for web and native user interfaces.","html_url":"https://github.com/facebook/react","language":"JavaScript","stargazers_count":242927,"forks_count":50550,"open_issues_count":1116,"updated_at":"2026-02-10T21:23:29Z","created_at":"2013-05-24T16:15:54Z","topics":["declarative","frontend","javascript","library","react","ui"],"private":false,"fork":false,"archived":false,"default_branch":"main"},{"id":70107786,"name":"next.js","full_name":"vercel/next.js","description":"The React Framework","html_url":"https://github.com/vercel/next.js","language":"JavaScript","stargazers_count":137594,"forks_count":30430,"open_issues_count":3305,"updated_at":"2026-02-10T21:33:50Z","created_at":"2016-10-05T23:32:51Z","topics":["blog","browser","compiler","components","hybrid","nextjs","node","react","server-rendering","ssg","static","static-site-generator","universal","vercel"],"private":false,"fork":false,"archived":false,"default_branch":"canary"},{"id":63537249,"name":"create-react-app","full_name":"facebook/create-react-app","description":"Set up a modern web app by running one command.","html_url":"https://github.com/facebook/create-react-app","language":"JavaScript","stargazers_count":103943,"forks_count":27138,"open_issues_count":2367,"updated_at":"2026-02-10T16:34:12Z","created_at":"2016-07-17T14:55:11Z","topics":["build-tools","react","zero-configuration"],"private":false,"fork":false,"archived":false,"default_branch":"main"},{"id":23083156,"name":"material-ui","full_name":"mui/material-ui","description":"Material UI: Comprehensive React component library that implements Google\'s Material Design. Free forever.","html_url":"https://github.com/mui/material-ui","language":"JavaScript","stargazers_count":97788,"forks_count":32772,"open_issues_count":1740,"updated_at":"2026-02-10T18:36:57Z","created_at":"2014-08-18T19:11:54Z","topics":["design-system","material-design","material-ui","react","react-components"],"private":false,"fork":false,"archived":false,"default_branch":"master"},{"id":147350463,"name":"33-js-concepts","full_name":"leonardomso/33-js-concepts","description":"📜 33 JavaScript concepts every developer should know.","html_url":"https://github.com/leonardomso/33-js-concepts","language":"JavaScript","stargazers_count":66250,"forks_count":9194,"open_issues_count":0,"updated_at":"2026-02-10T20:04:55Z","created_at":"2018-09-04T13:27:04Z","topics":["angular","concepts","es6","es6-javascript","hacktoberfest","javascript","javascript-closures","javascript-engines","javascript-programming","nodejs","primitive-types","programming","react"],"private":false,"fork":false,"archived":false,"default_branch":"master"}]}',
            annotations=None,
            meta=None,
        )
    ],
    structured_content=None,
    meta=None,
    data=None,
    is_error=False,
)
